name: DH-G2Final Deploy AWS Infrastructure

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout código
              uses: actions/checkout@v3

            - name: Login a GHCR
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

            - name: Construir imagen Docker
              run: docker build -t ghcr.io/${{ github.repository }}/backend:latest .

            - name: Subir imagen a GHCR
              run: docker push ghcr.io/${{ github.repository }}/backend:latest

    terraform:
        name: Infraestructura en AWS
        runs-on: ubuntu-latest

        steps:
            - name: Checkout del repositorio
              uses: actions/checkout@v3

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.5.0

            - name: Inicializar Terraform
              run: terraform init

            - name: Plan Terraform Changes
              run: terraform plan

            - name: Apply Terraform Changes
              run: terraform apply -auto-approve
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    deploy:
        name: Desplegar la aplicación en EC2
        runs-on: ubuntu-latest
        needs: terraform

        steps:
            - name: Checkout del repositorio
              uses: actions/checkout@v3

            - name: SSH into EC2 and deploy
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ec2-user
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd /home/ec2-user/app || git clone https://github.com/usuario/repo.git /home/ec2-user/app
                      cd /home/ec2-user/app
                      git pull origin main
                      sudo docker stop backend || true
                      sudo docker rm backend || true
                      sudo docker login ghcr.io -u <TU_USUARIO_GITHUB> -p <TOKEN_GITHUB>
                      sudo docker pull ghcr.io/<TU_USUARIO_GITHUB>/<TU_REPO>:latest
                      sudo docker stop backend || true
                      sudo docker rm backend || true
                      sudo docker run -d -p 8080:8080 --name backend ghcr.io/<TU_USUARIO_GITHUB>/<TU_REPO>:latest



name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies & Build
        run: |
          npm install
          npm run build

      - name: Upload to S3 with Cache-Control
        run: |
          aws s3 sync build/ s3://tu-bucket-s3/ --delete \
            --cache-control "max-age=31536000, public"
          aws s3 cp build/index.html s3://tu-bucket-s3/ \
            --cache-control "no-cache, no-store, must-revalidate"

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id TU_DISTRIBUTION_ID \
            --paths "/*"
